version: "3.2"
volumes:
  krb5kdc-data:
  keytabs:

services:
  php:
    image: php:latest
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
      - keytabs:/tmp/
  apache:
    image: apache:latest
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
      - keytabs:/tmp/
  kdc:
     image: krb5-server:latest
     restart: unless-stopped
     ports:
      - "88:88"
      - "464:464"
      - "749:749"
     environment:
       KRB5_REALM: EXAMPLE.COM
       KRB5_KDC: localhost
       KRB5_PASS: admin
     volumes:
      - krb5kdc-data:/var/lib/krb5kdc
      - keytabs:/tmp/
networks:
  frontend:
  backend:
